# Generated by Django 3.1.3 on 2021-12-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_data',
            new_name='NewsData',
        ),
    ]
