# Generated by Django 3.1.3 on 2021-12-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0002_auto_20211216_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='author',
            field=models.CharField(default='', max_length=40),
        ),
    ]
